# Use root/example as user/password credentials
version: '3.4'

services:

  db:
    image: mariadb/server:10.1
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
    my-db:
